import Header from '@/components/Header'
import ProviderWrapper from '@/lib/StoreWrapper'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ProviderWrapper>
			<html lang='ru'>
				<body>
					<Header />
					{children}
				</body>
			</html>
		</ProviderWrapper>
	)
}
